export const names = [
  "Adam Hochschild",
  "Adaner Usmani",
  "Allison Stanger",
  "Andrew Moravcsik",
  "Andrew Solomon",
  "Anne Applebaum",
  "Anne-Marie Slaughter",
  "Anthony Grafton",
  "Anthony Kronman",
  "Arlie Russell Hochschild",
  "Atul Gawande",
  "Bari Weiss",
  "Bill T. Jones",
  "Caitlin Flanagan",
  "Caroline Weber",
  "Cary Nelson",
  "Cathy Young",
  "Chloe Valdary",
  "Chloé Valdary",
  "Claire Bond Potter",
  "Coleman Hughes",
  "Cornel West",
  "Cynthia Tucker",
  "Dael Orlandersmith",
  "Dahlia Lithwick",
  "Damon Linker",
  "Daniel Kehlmann",
  "Daryl Michael Scott",
  "David Bromwich",
  "David Brooks",
  "David Frum",
  "David Greenberg",
  "David W. Blight",
  "Deborah Solomon",
  "Debra Mashek",
  "Deirdre McCloskey",
  "Dexter Filkins",
  "Diana Senechal",
  "Drucilla Cornell",
  "Elliot Ackerman",
  "Emily Yoffe",
  "Enrique Krauze",
  "Eric K. Washington",
  "Eva Hoffman",
  "Fareed Zakaria",
  "Federico Finchelstein",
  "Frances D. Cook",
  "Frances Kissling",
  "Francis Fukuyama",
  "Garry Kasparov",
  "Garry Wills",
  "George Packer",
  "Gerald Early",
  "Gloria Steinem",
  "Greg Pardlo",
  "Greil Marcus",
  "Helen Vendler",
  "Hussein Ibish",
  "Ian Buruma",
  "J. K. Rowling",
  "J.K. Rowling",
  "Jeet Heer",
  "Jeffrey Eugenides",
  "Jennifer Finney Boylan",
  "Jennifer Ratner-Rosenhagen",
  "Jennifer Senior",
  "Jesse Singal",
  "John Banville",
  "John McWhorter",
  "John R. MacArthur",
  "Jonathan Haidt",
  "Jonathan Rauch",
  "Joy Ladin",
  "Judith Shulevitz",
  "Judy B. Walzer",
  "Kamel Daoud",
  "Karim Sadjadpour",
  "Kat Rosenfield",
  "Katha Pollitt",
  "Kati Marton",
  "Katie Herzog",
  "Khaled Khalifa",
  "Kian Tajbakhsh",
  "Kim Ghattas",
  "Kmele Foster",
  "Laura Kipnis",
  "Lea Carpenter",
  "Letty Cottin Pogrebin",
  "Linda Greenhouse",
  "Loretta J. Ross",
  "Louis Begley",
  "Malcolm Gladwell",
  "Margaret Atwood",
  "Marie Arana",
  "Mark Lilla",
  "Mark Oppenheimer",
  "Martin Amis",
  "Matthew Karp",
  "Matthew Yglesias",
  "Meera Nanda",
  "Meghan Daum",
  "Melvin Rogers",
  "Mia Bay",
  "Michael Ignatieff",
  "Michael Walzer",
  "Michelle Goldberg",
  "Molly Worthen",
  "Nadine Strossen",
  "Neil Blair",
  "Neil Roberts",
  "Nell Irvin Painter",
  "Nicholas A. Christakis",
  "Nicholas Christakis",
  "Nicholas Lemann",
  "Noam Chomsky",
  "Olivia Nuzzi",
  "Orlando Patterson",
  "Parag Khanna",
  "Paul Berman",
  "Paul Starr",
  "Phoebe Maltz Bovy",
  "Randall Kennedy",
  "Randi Weingarten",
  "Rebecca Goldstein",
  "Reginald Dwayne Betts",
  "Richard T. Ford",
  "Rinne B. Groff",
  "Robert F. Worth",
  "Roger Berkowitz",
  "Roger Cohen",
  "Ronald S. Sullivan Jr.",
  "Roya Hakakian",
  "Saladin Ambar",
  "Salman Rushdie",
  "Samuel Moyn",
  "Sarah Haider",
  "Sean Wilentz",
  "Shadi Hamid",
  "Sheri Berman",
  "Steven Lukes",
  "Steven Pinker",
  "Susan Madrak",
  "Susannah Heschel",
  "Susie Linfield",
  "Taufiq Rahim",
  "Thomas Chatterton Williams",
  "Todd Gitlin",
  "Uday Mehta",
  "Wendell Steavenson",
  "Wendy Kaminer",
  "Wynton Marsalis",
  "Yascha Mounk",
  "Zaid Jilani",
  "Zephyr Teachout",
  "Zia Haider Rahman",
];
