export const names = [
  "Elliot Ackerman",
  "Saladin Ambar",
  "Martin Amis",
  "Anne Applebaum",
  "Marie Arana",
  "Margaret Atwood",
  "John Banville",
  "Mia Bay",
  "Louis Begley",
  "Roger Berkowitz",
  "Paul Berman",
  "Sheri Berman",
  "Reginald Dwayne Betts",
  "Neil Blair",
  "David W. Blight",
  "Jennifer Finney Boylan",
  "David Bromwich",
  "David Brooks",
  "Ian Buruma",
  "Lea Carpenter",
  "Noam Chomsky",
  "Nicholas Christakis",
  "Roger Cohen",
  "Frances D. Cook",
  "Drucilla Cornell",
  "Kamel Daoud",
  "Meghan Daum",
  "Gerald Early",
  "Jeffrey Eugenides",
  "Dexter Filkins",
  "Federico Finchelstein",
  "Caitlin Flanagan",
  "Richard T. Ford",
  "Kmele Foster",
  "David Frum",
  "Francis Fukuyama",
  "Atul Gawande",
  "Todd Gitlin",
  "Kim Ghattas",
  "Malcolm Gladwell",
  "Michelle Goldberg",
  "Rebecca Goldstein",
  "Anthony Grafton",
  "David Greenberg",
  "Linda Greenhouse",
  "Rinne B. Groff",
  "Sarah Haider",
  "Jonathan Haidt",
  "Roya Hakakian",
  "Shadi Hamid",
  "Jeet Heer",
  "Katie Herzog",
  "Susannah Heschel",
  "Adam Hochschild",
  "Arlie Russell Hochschild",
  "Eva Hoffman",
  "Coleman Hughes",
  "Hussein Ibish",
  "Michael Ignatieff",
  "Zaid Jilani",
  "Bill T. Jones",
  "Wendy Kaminer",
  "Matthew Karp",
  "Garry Kasparov",
  "Daniel Kehlmann",
  "Randall Kennedy",
  "Khaled Khalifa",
  "Parag Khanna",
  "Laura Kipnis",
  "Frances Kissling",
  "Enrique Krauze",
  "Anthony Kronman",
  "Joy Ladin",
  "Nicholas Lemann",
  "Mark Lilla",
  "Susie Linfield",
  "Damon Linker",
  "Dahlia Lithwick",
  "Steven Lukes",
  "John R. MacArthur",
  "Susan Madrak",
  "Phoebe Maltz Bovy",
  "Greil Marcus",
  "Wynton Marsalis",
  "Kati Marton",
  "Debra Mashek",
  "Deirdre McCloskey",
  "John McWhorter",
  "Uday Mehta",
  "Andrew Moravcsik",
  "Yascha Mounk",
  "Samuel Moyn",
  "Meera Nanda",
  "Cary Nelson",
  "Olivia Nuzzi",
  "Mark Oppenheimer",
  "Dael Orlandersmith",
  "George Packer",
  "Nell Irvin Painter",
  "Greg Pardlo",
  "Orlando Patterson",
  "Steven Pinker",
  "Letty Cottin Pogrebin",
  "Katha Pollitt",
  "Claire Bond Potter",
  "Taufiq Rahim",
  "Zia Haider Rahman",
  "Jennifer Ratner‑Rosenhagen",
  "Jonathan Rauch",
  "Neil Roberts",
  "Melvin Rogers",
  "Kat Rosenfield",
  "Loretta J. Ross",
  "J. K. Rowling",
  "Salman Rushdie",
  "Karim Sadjadpour",
  "Daryl Michael Scott",
  "Diana Senechal",
  "Jennifer Senior",
  "Judith Shulevitz",
  "Jesse Singal",
  "Anne‑Marie Slaughter",
  "Andrew Solomon",
  "Deborah Solomon",
  "Allison Stanger",
  "Paul Starr",
  "Wendell Steavenson",
  "Gloria Steinem",
  "Nadine Strossen",
  "Ronald S. Sullivan Jr.",
  "Kian Tajbakhsh",
  "Zephyr Teachout",
  "Cynthia Tucker",
  "Adaner Usmani",
  "Chloé Valdary",
  "Helen Vendler",
  "Judy B. Walzer",
  "Michael Walzer",
  "Eric K. Washington",
  "Caroline Weber",
  "Randi Weingarten",
  "Bari Weiss",
  "Cornel West",
  "Sean Wilentz",
  "Garry Wills",
  "Thomas Chatterton Williams",
  "Robert F. Worth",
  "Molly Worthen",
  "Matthew Yglesias",
  "Emily Yoffe",
  "Cathy Young",
  "Fareed Zakaria",
];
